"""empty message

Revision ID: a79bcd067add
Revises: 
Create Date: 2023-01-29 17:35:18.631298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79bcd067add'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_dep', sa.String(length=40), nullable=True),
    sa.Column('presupuesto_anual', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habilidadempleado',
    sa.Column('codigohabilidad', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('codigohabilidad')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=88), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('empleado',
    sa.Column('rif', sa.String(length=20), nullable=False),
    sa.Column('fecha_ingreso_emp', sa.Date(), nullable=True),
    sa.Column('nombre_empleado', sa.String(length=60), nullable=True),
    sa.Column('apellidoP_empleado', sa.String(length=60), nullable=True),
    sa.Column('apellidoM_empleado', sa.String(length=60), nullable=True),
    sa.Column('tlf_movil_emp', sa.String(length=32), nullable=True),
    sa.Column('tlf_fijo_emp', sa.String(length=32), nullable=True),
    sa.Column('num_hijos', sa.Integer(), nullable=True),
    sa.Column('salario', sa.Numeric(), nullable=True),
    sa.Column('codigo_dep_emp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_dep_emp'], ['departamento.id'], ),
    sa.PrimaryKeyConstraint('rif')
    )
    op.create_table('centrotrabajo',
    sa.Column('id_centro', sa.Integer(), nullable=False),
    sa.Column('calle_av', sa.String(length=60), nullable=True),
    sa.Column('ciudad_centro', sa.String(length=60), nullable=True),
    sa.Column('estado_centro', sa.String(length=60), nullable=True),
    sa.Column('poblacion_centro', sa.Integer(), nullable=True),
    sa.Column('codigo_departamento', sa.Integer(), nullable=True),
    sa.Column('codigo_jefe', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['codigo_departamento'], ['departamento.id'], ),
    sa.ForeignKeyConstraint(['codigo_jefe'], ['empleado.rif'], ),
    sa.PrimaryKeyConstraint('id_centro')
    )
    op.create_table('empleadohijos',
    sa.Column('codigohijo', sa.Integer(), nullable=False),
    sa.Column('nombre_hijo', sa.String(length=60), nullable=True),
    sa.Column('apellidoP_hijo', sa.String(length=60), nullable=True),
    sa.Column('apellidoM_hijo', sa.String(length=60), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('empleado_padre', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['empleado_padre'], ['empleado.rif'], ),
    sa.PrimaryKeyConstraint('codigohijo')
    )
    op.create_table('habilidades_empleados',
    sa.Column('id_emphab', sa.Integer(), nullable=False),
    sa.Column('empleado_rif', sa.String(length=20), nullable=True),
    sa.Column('habilidad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_rif'], ['empleado.rif'], ),
    sa.ForeignKeyConstraint(['habilidad_id'], ['habilidadempleado.codigohabilidad'], ),
    sa.PrimaryKeyConstraint('id_emphab')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habilidades_empleados')
    op.drop_table('empleadohijos')
    op.drop_table('centrotrabajo')
    op.drop_table('empleado')
    op.drop_table('usuario')
    op.drop_table('habilidadempleado')
    op.drop_table('departamento')
    # ### end Alembic commands ###
